services:
  - type: web
    name: soto-hr-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python soto_tracker.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8 