services:
  - type: web
    name: alonso-at-bat-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python alonso_tracker.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4 