services:
  - type: web
    name: soto-hr-tracker
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: PYTHONUNBUFFERED
        value: "1" 